### ISSUE TITLE
NID 2016 - Assignment 2 (Generative Art using P5.js)

### ISSUE THREAD

**Issue by rasagy** [rasagy/data-art-101#2]
Share some of the experiments (screenshots/gif) that you have created today using [P5.js](p5js.org), and feel free to link to any projects you’ve hosted as well.

Here are some of the selected examples of abstract art pieces for inspiration (more on [Pinterest](https://in.pinterest.com/rasagy/textures-patterns-computational-art/)!)

_Andre Volten - Composition no. 12. (1957)_
![andre volten - composition no 12 1957](https://cloud.githubusercontent.com/assets/1117531/19621470/645b9b0a-98b0-11e6-9635-de8dc44bf4b3.jpg)

_Inspiration from [Daily Minimal](http://www.dailyminimal.com/)_
![daily minimal](https://cloud.githubusercontent.com/assets/1117531/19621502/f3093c22-98b0-11e6-9791-1337938a957f.jpg)

_Herbert Bayer - Red Transparency (1969-1973)_
![red transparency 1969-1973 herbert bayer](https://cloud.githubusercontent.com/assets/1117531/19621487/b7e6a3dc-98b0-11e6-9c84-e6b3c24dba65.jpg)

_Inspiration from [Geometry Daily](http://geometrydaily.tumblr.com/)_
![geometry daily - binary suns](https://cloud.githubusercontent.com/assets/1117531/19621511/0e80a0bc-98b1-11e6-967c-6a13e93f7d5f.jpg)

**Comment by pkd2512** [comment]
function setup() {
  createCanvas(600,600);
  fill('red');
  
  noStroke();
  
  ellipse(300,300,100,100);
  fill('yellow');
  ellipse(300,200,50,200);
  
  ellipse(200,300,200,50);
  
  ellipse(300,400,50,200);
  
  ellipse(400,300,200,50);
  
  //fill(255,0,0,150);
  ellipse(300,200,50,200);
  
  ellipse(200,300,200,50);
  
  ellipse(300,400,50,200);
  
  ellipse(400,300,200,50);
  fill(255,255,0,150);
  ellipse(300,300,50);
  
 
}

function draw() {
  
}

**Comment by rasagy** [comment]
Here’s one of the programs that I made in class: Uses sin() & cos() to move a circle, angle to select hue, and mouseX for size of circle. You can [play with it here](http://rasagy.in/data-art-101/examples/rotating-circle). Feel free to look at the [source code](https://github.com/rasagy/data-art-101/blob/master/examples/rotating-circle/sketch.js).

![bubble-circle](https://cloud.githubusercontent.com/assets/1117531/19621584/69ad313e-98b2-11e6-9f9d-f930e28c298c.gif)

**Comment by rasagy** [comment]
@pkd2512 Try sharing some screenshots or gifs instead of the source code! ☺️

**Comment by Siddhantmd** [comment]
![cursor changing color and size](https://cloud.githubusercontent.com/assets/22995848/19627892/53559102-996f-11e6-8b2d-c7bd3ffc9f73.gif)

Hi, this is a work in progress. The colors,position and size of the ellipses which follow the cursor are functions of mouse pointer coordinates. 
I wanted the cursor size to increase as it approaches the center of the screen and reduce as it moves away. But have not been able to achieve this accurately yet. Working on it. 

One more thing. is this correct way to share our work? Or should I do it in some other manner?

**Comment by Siddhantmd** [comment]
![cursor with center marker](https://cloud.githubusercontent.com/assets/22995848/19629202/b80f4c60-998c-11e6-9648-91673fe95bc2.gif)
Ok, success

**Comment by vinodxyz** [comment]
Hello, Tried out P5.js out to make [this](http://htmldotafreak.github.io/Ripples/). It's really kinda addictive. 😄  (source code: [here](https://github.com/HTMLdotafreak/HTMLdotafreak.github.io/blob/master/Ripples/sketch.js)) Let me know what you think. Thanks.

**Comment by rasagy** [comment]
@Siddhantmd Sweet, that’s looking pretty good! In terms of next stages, you could play with some [rotation](https://p5js.org/reference/#/p5/rotate) to continously keep rotating the circles along with the mouse interaction. And maybe try a few more shapes next!

As for sharing your work, GIFs are great to give a glimpse of what you’ve made (& [LiceCap](http://www.cockos.com/licecap/) is for both Win & Mac!), and you can always host your projects like @HTMLdotafreak has done to share an interactive version as well! 😉 

@HTMLdotafreak Looking great, and nice to have that hosted on Github! You could next try and work more on the colors that are selected (maybe each burst could have variations of one hue, or a gradual change from one hue to another?) and then think of some interactivity as well (maybe the bursts could happen when you click, or around the area your mouse is?). Love the _BOOM!_ text btw! 👍 

Keep sharing your work here, and help out your peers with hosting their projects on Github as well! 😄

**Comment by rasagy** [comment]
For some more ideas, a few projects that I’ve played around with that I showed in the class are hosted on my [Processing-playground repo](https://github.com/rasagy/processing-playground#processing-playground). There are also several more examples available on [OpenProcessing](https://www.openprocessing.org/browse/?q=&time=thisMonth&type=hearts#) where you can also host your P5.js code!

**Comment by vinodxyz** [comment]
Thanks a lot, Rasagy. 😃  Will add the changes you mentioned. Sounds cool.
Also, Loved your projects, might copy a few ideas and play around. 😉

**Comment by Siddhantmd** [comment]
Thanks Rasagy 😃   I will try the rotation too. Was thinking of adding more functions. Will share when I do.  Saw your projects. Inspiring stuff

**Comment by Siddhantmd** [comment]
![powers pyramid](https://cloud.githubusercontent.com/assets/22995848/19657266/0d93134c-9a41-11e6-9a49-6003e743d74a.PNG)

Here's something else I made. Using nested for loops. Each row has (no. of row)^2 cells

**Comment by Siddhantmd** [comment]
![linear pattern series](https://cloud.githubusercontent.com/assets/22995848/19920159/03b178ec-a0fd-11e6-88ef-ab50602d85b5.gif)
![linear pattern series2](https://cloud.githubusercontent.com/assets/22995848/19920160/03b5eea4-a0fd-11e6-925a-7f37348ee241.gif)

Random no. of line segments, each beginning where the last ended. Random colors and random stroke weight bw 0-20
