### ISSUE TITLE
Assignment 1: Imitat10n — Recreating abstract paintings

### ISSUE THREAD

**Issue by rasagy** [rasagy/data-art-101#3]
Goal: Recreate one of the [abstract paintings from this Pinterest board](https://in.pinterest.com/rasagy/artists-abstract-geometric-modern/) (or something similar):

1. As a static version
2. With some randomness
3. With some interactivity

Upload each of these on [OpenProcessing](http://openprocessing.org), and add a comment below with one screenshot/gif and link each, along with the name of the painting & the artist.

To take a screenshot of the canvas, you can [use saveCanvas() like this](https://editor.p5js.org/rasagy/sketches/SJH_KD7CO).

**Comment by rasagy** [comment]
Example:
My painting was Piet Mondrian’s Block Party.

![Screen Shot 2019-07-31 at 3 14 34 PM](https://user-images.githubusercontent.com/1117531/62202145-601d8080-b3a6-11e9-9460-003d6bd4d4f6.png)

[Link for source](https://www.openprocessing.org/sketch/741467)

**Comment by Ipsha13** [comment]
Recreating Dots & Circles by MuirMcNeil

STATIC:
A) Poster by MuirMcNeil
find on pinterest: https://in.pinterest.com/pin/218917231863786032/
Website for artist: http://www.muirmcneil.com/


![4bc5bcc5b91eb9be4afcc20a5cae56cc](https://user-images.githubusercontent.com/47627914/62204149-3c5c3980-b3aa-11e9-8651-afea2b200d7f.jpg)


![image](https://user-images.githubusercontent.com/47627914/62202853-b63ef380-b3a7-11e9-8cd5-a4269ae3fee8.png)

Link for Source: https://www.openprocessing.org/sketch/741468

**Comment by sankson** [comment]
Homage to the Square (La Tehuana) - Josef Albers
![Homage to the Square (La Tehuana) - Josef Albers](https://user-images.githubusercontent.com/52407137/62204343-a5dc4800-b3aa-11e9-88e3-e6a847d1dd1e.jpg)

Recreating Homage to the Square (La Tehuana) - Josef Albers
![image](https://user-images.githubusercontent.com/52407137/62203139-3b2a0d00-b3a8-11e9-928f-add1bca6bec0.png)

Homage with animation
![Homage](https://user-images.githubusercontent.com/52407137/62204975-fb652480-b3ab-11e9-9e57-af7d849fe011.gif)



Source code:https://www.openprocessing.org/sketch/741466

**Comment by DeshnaSV** [comment]
Recreating formulations by Josef Albers
<img width="301" alt="Screenshot 2019-07-31 at 3 32 24 PM" src="https://user-images.githubusercontent.com/52406999/62203282-77f60400-b3a8-11e9-8e62-ffedf41bfd5d.png">

Find the source code at https://www.openprocessing.org/sketch/741473

Recreating Circles in a Circle by Wassily Kandinsky, 1923
<img width="349" alt="Screenshot 2019-07-29 at 10 28 58 PM" src="https://user-images.githubusercontent.com/52406999/62278702-3c217400-b466-11e9-825d-ef845e8a0ce2.png">

My interpretation

<img width="606" alt="Screenshot 2019-08-01 at 2 07 21 PM" src="https://user-images.githubusercontent.com/52406999/62279014-dd102f00-b466-11e9-871a-cc55c621b515.png">

![Kandinsky-circles](https://user-images.githubusercontent.com/52406999/62279023-e3061000-b466-11e9-8ea5-7cf38ecb3236.gif)

The source code is available on [Open Processing](https://www.openprocessing.org/sketch/741732)

**Comment by Tanaya01** [comment]
Recreating László Mohloy Nagy's Painting

<img width="456" alt="Screenshot 2019-07-31 at 3 25 22 PM" src="https://user-images.githubusercontent.com/47748863/62203480-e5099980-b3a8-11e9-93a3-d67f0c513e09.png">

![Abstract 2 0](https://user-images.githubusercontent.com/47748863/62204656-4b8fb700-b3ab-11e9-922b-459b6f3f5ba2.gif)

![hh](https://user-images.githubusercontent.com/47748863/62290270-929aac80-b47e-11e9-9af3-875ef46c25b6.gif)

https://www.openprocessing.org/sketch/741471

**Comment by AishwaryaAnandSingh** [comment]
A) Laszlo Moholy-Nagy
![df8b1104e4732654d516089952408bef](https://user-images.githubusercontent.com/52406831/62203132-36655900-b3a8-11e9-9067-6735082d956a.jpg)



Static:
<img width="649" alt="Screenshot 2019-07-31 at 3 33 39 PM" src="https://user-images.githubusercontent.com/52406831/62203355-9f4cd100-b3a8-11e9-8c59-9167fa0ed01b.png">

https://www.openprocessing.org/sketch/741483

Animated:
1. Random
![Painting Random](https://user-images.githubusercontent.com/52406831/62203386-b095dd80-b3a8-11e9-8d39-6ffdd8e22a37.gif)
https://www.openprocessing.org/sketch/741484

2. Interactive
![Painting Interactive](https://user-images.githubusercontent.com/52406831/62203422-c2778080-b3a8-11e9-9813-5da10933b1b4.gif)
https://www.openprocessing.org/sketch/741485



B)Yin Yan from the series Disc in a Square, 1970. Walter Dexel
![40cdf868c05930a51b3482ab55434d9a](https://user-images.githubusercontent.com/52406831/62203496-ed61d480-b3a8-11e9-9d88-5e65408d8cc0.jpg)


Animated
![Art](https://user-images.githubusercontent.com/52406831/62203523-f9e62d00-b3a8-11e9-84cd-bcf93388db77.gif)
https://www.openprocessing.org/sketch/741487


Jinju Jang - Medium
![1515dd0382e2c496b4c80c18a0bb75dc](https://user-images.githubusercontent.com/52406831/62288061-2e291e80-b479-11e9-8fbc-b92302b553ce.jpg)

Interactive
![CircleSS](https://user-images.githubusercontent.com/52406831/62288081-397c4a00-b479-11e9-9291-56e08703766a.gif)

https://www.openprocessing.org/sketch/742556

**Comment by okshyeah-nid** [comment]
### Source code
https://www.openprocessing.org/sketch/741477

### Static
<img width="397" alt="Screenshot 2019-07-31 at 3 37 33 PM" src="https://user-images.githubusercontent.com/44680006/62203698-4b8eb780-b3a9-11e9-9eae-428855758e32.png">

### Animated
![Ivan_serpa](https://user-images.githubusercontent.com/44680006/62204253-7b8a8a80-b3aa-11e9-94b4-1b8c7ed7f101.gif)

**Comment by anurag24395sachan** [comment]
**1. Original Painting by Laszlo Moholy-Nagy-**

![730cf5c025fc20adc389948c6841e8a0](https://user-images.githubusercontent.com/52406963/62203656-39147e00-b3a9-11e9-8d5b-2bf9b1d0497a.jpg)


**Static:**
![Painting](https://user-images.githubusercontent.com/52406963/62203542-05d1ef00-b3a9-11e9-8617-890b5abf07e7.JPG)

**GIF of Interaction with Mouse(Parallax):**
![Painting_Parallax](https://user-images.githubusercontent.com/52406963/62203743-619c7800-b3a9-11e9-8f68-460d793f4a4a.gif)

Link:https://www.openprocessing.org/sketch/741474

**2. Truchet Tiles**
![TriangleAnimation-1 (1)](https://user-images.githubusercontent.com/52406963/62411086-3b2a4700-b60c-11e9-963c-3da0b7fffe6f.png)
![TriangleAnimation-1](https://user-images.githubusercontent.com/52406963/62411089-3ebdce00-b60c-11e9-802d-b63bf740d3e3.png)

Link: https://www.openprocessing.org/sketch/742219

**3.1: Explorations with Random function**

![Screen Shot 2019-08-02 at 1 19 35 PM](https://user-images.githubusercontent.com/52406963/62411128-91978580-b60c-11e9-88d4-a64b78c87fb3.png)
![Screen Shot 2019-08-02 at 1 19 41 PM](https://user-images.githubusercontent.com/52406963/62411131-978d6680-b60c-11e9-9a78-7bcc01a1de53.png)
![Screen Shot 2019-08-02 at 1 19 47 PM](https://user-images.githubusercontent.com/52406963/62411136-9ceab100-b60c-11e9-8026-3aaaf12a4fec.png)

Link: https://www.openprocessing.org/sketch/742221

 **3.2: Explorations with Random function**
![Screen Shot 2019-08-02 at 3 53 26 PM](https://user-images.githubusercontent.com/52406963/62411158-c3105100-b60c-11e9-95d5-c80ee56fe63a.png)
![Screen Shot 2019-08-02 at 3 53 30 PM](https://user-images.githubusercontent.com/52406963/62411160-c4da1480-b60c-11e9-8e3a-2e1d2aeee00e.png)
![Screen Shot 2019-08-02 at 3 53 36 PM](https://user-images.githubusercontent.com/52406963/62411162-c6a3d800-b60c-11e9-8664-53f0a99f732e.png)

Link: https://www.openprocessing.org/sketch/742223

**4: Looping Animations**

![TriangleAnimation](https://user-images.githubusercontent.com/52406963/62411215-7416eb80-b60d-11e9-91b1-facf1c18534f.gif)

Link: https://www.openprocessing.org/sketch/742222

![Dot-Animation](https://user-images.githubusercontent.com/52406963/62411235-9f99d600-b60d-11e9-94c3-fd9cfb25e9a6.gif)

Link: https://www.openprocessing.org/sketch/742224

**Comment by RoopamSonpethkar** [comment]
Painting by Ivan Serpa
![f8bd22069bac00ff3a4ccf4a20e4b11b](https://user-images.githubusercontent.com/47752434/62219324-bea92580-b3cb-11e9-848b-df6cd792d34a.jpg)

![Painting](https://user-images.githubusercontent.com/47752434/62203847-9a3c5180-b3a9-11e9-8b4c-7e5e57e4b2c1.gif)
Code :https://editor.p5js.org/RoopamSonpethkar/sketches/EdbODAU-f

![m nonsttic 1](https://user-images.githubusercontent.com/47752434/62203962-d8d20c00-b3a9-11e9-87ec-a954864a930b.gif)
Code:https://editor.p5js.org/RoopamSonpethkar/sketches/6YiSXxUDO

**Comment by kanchanrpathak** [comment]
![image](https://user-images.githubusercontent.com/13308318/62204191-56961780-b3aa-11e9-812c-b87f8f85c60d.png)

**Comment by kanchanrpathak** [comment]
Nervousness
![nervousness](https://user-images.githubusercontent.com/13308318/62204227-69a8e780-b3aa-11e9-9cab-2270eaad8e31.gif)

**Comment by kanchanrpathak** [comment]
Nervousness
![nervousness](https://user-images.githubusercontent.com/13308318/62204349-aa086580-b3aa-11e9-8efb-a67c96fbc7c7.gif)
https://editor.p5js.org/kanchan_p/sketches/5XHHKaWpE

**Comment by kanchanrpathak** [comment]
Jailed
<img width="400" alt="Screenshot 2019-07-31 at 3 55 09 PM" src="https://user-images.githubusercontent.com/13308318/62204825-a4f7e600-b3ab-11e9-9738-bd119d4633f3.png">


![jailed](https://user-images.githubusercontent.com/13308318/62204708-62cea480-b3ab-11e9-9d83-dd1b7602c4ff.gif)

https://editor.p5js.org/kanchan_p/sketches/yS9JEMlHJ

**Comment by preetigiri** [comment]
https://www.openprocessing.org/sketch/741491

reference: HILMA AF KLINT

**Comment by raktimb** [comment]
Painting by Hilma af Klint
<img width="360" alt="Screenshot 2019-07-31 at 3 59 23 PM" src="https://user-images.githubusercontent.com/47768718/62205070-37988500-b3ac-11e9-815d-e4595b351b25.png">


Static replica
<img width="400" alt="Screenshot 2019-07-31 at 3 57 23 PM" src="https://user-images.githubusercontent.com/47768718/62205112-539c2680-b3ac-11e9-96b2-0c5daa69d2ba.png">



Interactive replica
Link: https://www.openprocessing.org/sketch/741489
![interactive](https://user-images.githubusercontent.com/47768718/62205162-74647c00-b3ac-11e9-92d7-577e37d121a6.gif)



Random replica
Link: https://www.openprocessing.org/sketch/741492
![random](https://user-images.githubusercontent.com/47768718/62205270-bb527180-b3ac-11e9-9e32-6aa6de644db2.gif)






Kandinsky Circles Poster
<img width="469" alt="Screenshot 2019-07-31 at 11 14 46 PM" src="https://user-images.githubusercontent.com/47768718/62235112-d7283880-b3e9-11e9-937a-3737881ab172.png">

Random replica
Link: https://www.openprocessing.org/sketch/741574
![random-kandinsky](https://user-images.githubusercontent.com/47768718/62235438-9a107600-b3ea-11e9-88fe-57753d06deee.gif)

**Comment by DarthElevator** [comment]
Recreating interaction of colours by Josef Albers.
![Albers-1](https://user-images.githubusercontent.com/34890610/62227861-4d24a380-b3da-11e9-86fb-d1a571f4b3bd.jpg)
The image above is the original
<img width="443" alt="Screenshot 2019-07-31 at 6 55 36 PM" src="https://user-images.githubusercontent.com/34890610/62227900-5f064680-b3da-11e9-9250-bc6481f4aeab.png">
And this above is my recreation 
https://www.openprocessing.org/sketch/741501

**Comment by DarthElevator** [comment]
And here is the random version which uses the same color palette but randomises it to give a tetris like feel.
![interaction-of-colour](https://user-images.githubusercontent.com/34890610/62270212-150d7700-b453-11e9-8c17-daa0c902a6f8.gif)

**Comment by preetigiri** [comment]
Reference art by Designer Bram Vanhaeren
![reference art](https://user-images.githubusercontent.com/46617575/62280447-8f48f600-b469-11e9-9afb-fa11b652b806.JPG)

My take on it
![my take](https://user-images.githubusercontent.com/46617575/62280547-c7e8cf80-b469-11e9-8e3b-cdbc278a3017.JPG)

https://www.openprocessing.org/sketch/741735

**Comment by DarthElevator** [comment]
Recreating Bauhaus school posters.
This is the one from 1923

This is the original
<img width="513" alt="Screenshot 2019-08-01 at 4 00 50 PM" src="https://user-images.githubusercontent.com/34890610/62286614-b7d6ed00-b475-11e9-85c0-440b27869379.png">

And this is the static recreation of that

<img width="580" alt="Screenshot 2019-08-01 at 4 13 37 PM" src="https://user-images.githubusercontent.com/34890610/62287473-8828e480-b477-11e9-8971-832b6792f169.png">
https://www.openprocessing.org/sketch/741746

**Comment by DarthElevator** [comment]
Tried to recreate this 1923 Bauhaus school poster
<img width="485" alt="original" src="https://user-images.githubusercontent.com/34890610/62288616-65e49600-b47a-11e9-88b8-0b3ce5157d8b.png">
This is my static recreation of the same

<img width="596" alt="Static" src="https://user-images.githubusercontent.com/34890610/62289587-b3fa9900-b47c-11e9-8b55-89132b8529c7.png">

And this is the interactive gif with a simple mouse hover

![interactive-bauhaus](https://user-images.githubusercontent.com/34890610/62290762-bad6db00-b47f-11e9-962a-5c9805dd8b77.gif)

**Comment by Ipsha13** [comment]
The Multiplication Curve


Source Code: https://www.openprocessing.org/sketch/741747

![image](https://user-images.githubusercontent.com/47627914/62288645-75fc7580-b47a-11e9-9a36-bd0ee06a484d.png)

**Comment by Ipsha13** [comment]
The Multiplication Squares
Source Code: https://www.openprocessing.org/sketch/741748

![image](https://user-images.githubusercontent.com/47627914/62289442-62eaa500-b47c-11e9-81f1-882affc1f3da.png)

**Comment by DarthElevator** [comment]
And this is the interactive gif with a simple mouse hover

![interactive-bauhaus](https://user-images.githubusercontent.com/34890610/62290762-bad6db00-b47f-11e9-962a-5c9805dd8b77.gif)

**Comment by kanchanrpathak** [comment]
**Design for your name**

Name - Kanchan Pathak
![Squares - preeti giri-55](https://user-images.githubusercontent.com/13308318/62290767-bd393500-b47f-11e9-85a1-e2a904e60cca.png)

Name - Preeti Giri
![Circles - kanchan-65](https://user-images.githubusercontent.com/13308318/62290791-c75b3380-b47f-11e9-8e13-b48d96a3a43c.png)

Name - Kanchan 
![Squares - kanchan pathak-75](https://user-images.githubusercontent.com/13308318/62290711-9e3aa300-b47f-11e9-9d4c-d573b0bde417.png)

**Comment by rasagy** [comment]
These are looking great, thanks for the updates everyone!

**Comment by Ipsha13** [comment]
Recreating art piece by Verena Loewensberg
Date: 1980
Style: Concretism
Genre: abstract

Link: https://www.wikiart.org/en/verena-loewensberg/untitled-1980
Reference:
![cb3890859da484470b04d18f0d4a2dae](https://user-images.githubusercontent.com/47627914/62359844-40689280-b535-11e9-9030-741805c3299e.jpg)R

Recreated Art piece by Verena Loewensberg : Static
Source Code: https://www.openprocessing.org/sketch/741998

![image](https://user-images.githubusercontent.com/47627914/62360298-1b285400-b536-11e9-8cce-7216335b540d.png)


Recreated Art piece by Verena Loewensberg : Random
Source Code: https://www.openprocessing.org/sketch/741995
![new random](https://user-images.githubusercontent.com/47627914/62363031-e9b28700-b53b-11e9-9457-6e260b97e20f.gif)


Recreated Art piece by Verena Loewensberg : Interactive
Source Code: https://www.openprocessing.org/sketch/741996
![move mouse](https://user-images.githubusercontent.com/47627914/62362676-1ca84b00-b53b-11e9-9637-cd28cdc091e5.gif)



Recreated Art piece by Verena Loewensberg : Play / exploration
https://www.openprocessing.org/sketch/741997

![play](https://user-images.githubusercontent.com/47627914/62362728-3ea1cd80-b53b-11e9-93ef-f407a4fbabca.gif)

**Comment by shrav13** [comment]
FUTURE GLOBES by Matthew Korbel-Bowers
Link: https://in.pinterest.com/pin/316518680033996992/
![tumblr_ltmnppAUcN1qdj0hbo1_500](https://user-images.githubusercontent.com/33093334/63261214-82693680-c2a0-11e9-81a2-df7c8d2f7da6.jpg)

Recreated Art piece by Matthew Korbel-Bowers : Static
Source Code: https://www.openprocessing.org/sketch/745488
![canvas](https://user-images.githubusercontent.com/33093334/63261334-de33bf80-c2a0-11e9-9936-8bd04868901f.png)

Recreated Art piece by Matthew Korbel-Bowers : Animation
Source Code: https://www.openprocessing.org/sketch/745488
![Media122](https://user-images.githubusercontent.com/33093334/63265698-d4fc2000-c2ab-11e9-8e3f-841432272209.gif)

Recreated Art piece by Matthew Korbel-Bowers : Interactive
Source Code: https://www.openprocessing.org/sketch/745488
![Media2](https://user-images.githubusercontent.com/33093334/63265745-efce9480-c2ab-11e9-9bac-b41857ae2621.gif)
