### ISSUE TITLE
Assignment 2: Exploratory pieces

### ISSUE THREAD

**Issue by rasagy** [rasagy/data-art-101#4]
Here’s a thread to share what you’re creating in the next two days. The ideas that we had as of now:

## Viznam: Names creating art
[Starter code](https://editor.p5js.org/rasagy/sketches/i7pwsbj2r)
- Aishwarya - Constellation from names
- Kanchan - Geometric Mandalas from names
- Roopam - Abstract ~shapes~ sunset  from names
- Raktim - Spirals using names

## Generative patterns
- Deshna - Generative patterns from her scarves
- Tanaya - Expressive patterns for Rasas (Emotions)
- Ipsha - Expressive Maths
- Anurag - Looping animations

## Typography experiments
- Preeti - Expressive typography
- Anurag - Something with Typography

## Geometric compositions
- Nikhil - Geometric bauhaus posters
- Sanjay - Random geometric  composition, Indus Valley civilization grid

## ML experiments
- Jitesh - ML5.js based pose recognition

**Comment by DarthElevator** [comment]
Geometric Bauhaus posters
a recreation of the 1923 poster
<img width="485" alt="original" src="https://user-images.githubusercontent.com/34890610/62348056-739d2880-b519-11e9-96a4-6d2db35ceeb6.png">
This is the original

<img width="596" alt="Static" src="https://user-images.githubusercontent.com/34890610/62348075-80ba1780-b519-11e9-8dab-278c9940a4f0.png">

This is the static version that I recreated https://www.openprocessing.org/sketch/741746

![interactive-bauhaus](https://user-images.githubusercontent.com/34890610/62348099-94fe1480-b519-11e9-8e5c-bb692ec7e81c.gif)

This is the one that is interactive https://www.openprocessing.org/sketch/741749

**Comment by DarthElevator** [comment]
### **Another recreation of a Bauhaus poster. This one is from the 1923 exhibition**

<img width="437" alt="original-bauhaus" src="https://user-images.githubusercontent.com/34890610/62354396-5ae93e80-b52a-11e9-8228-fea27acffa9a.png">

**This is the original Bauhaus exhibition poster**

<img width="373" alt="static-recreation" src="https://user-images.githubusercontent.com/34890610/62354924-920c1f80-b52b-11e9-82ae-34cbda669b12.png">


**This is the static version that I recreated**


![tetris](https://user-images.githubusercontent.com/34890610/62364645-b671f700-b53f-11e9-92a4-44115729a4d3.gif)



**_This is the interactive version which is made to resemble like the video game Tetris_**
https://www.openprocessing.org/sketch/742003

<img width="368" alt="Typography" src="https://user-images.githubusercontent.com/34890610/62355183-237b9180-b52c-11e9-9ccf-b8c51c1c2b9e.png">

**This is the version with type added through P5**
https://www.openprocessing.org/sketch/742001

**Comment by DarthElevator** [comment]
### **This is the third one from the series of the Bauhaus exhibition 1923**

![Bau3-original](https://user-images.githubusercontent.com/34890610/62363668-6d20a800-b53d-11e9-901b-ed4136212e7f.jpg)

**This is the original one**
<img width="397" alt="Bau3-static" src="https://user-images.githubusercontent.com/34890610/62363594-48c4cb80-b53d-11e9-909c-2af05b95fbb0.png">

**This is the static version**

<img width="396" alt="Bauh3-static-with-type" src="https://user-images.githubusercontent.com/34890610/62363529-3054b100-b53d-11e9-8cc5-9cee19e28939.png">

**_The one with type_** https://www.openprocessing.org/sketch/742000

**Comment by anurag24395sachan** [comment]
**1. Original Painting by Laszlo Moholy-Nagy-**

![730cf5c025fc20adc389948c6841e8a0](https://user-images.githubusercontent.com/52406963/62203656-39147e00-b3a9-11e9-8d5b-2bf9b1d0497a.jpg)


**Static:**
![Painting](https://user-images.githubusercontent.com/52406963/62203542-05d1ef00-b3a9-11e9-8617-890b5abf07e7.JPG)

**GIF of Interaction with Mouse(Parallax):**
![Painting_Parallax](https://user-images.githubusercontent.com/52406963/62203743-619c7800-b3a9-11e9-8f68-460d793f4a4a.gif)

Link:https://www.openprocessing.org/sketch/741474

**2. Truchet Tiles**
![TriangleAnimation-1 (1)](https://user-images.githubusercontent.com/52406963/62411086-3b2a4700-b60c-11e9-963c-3da0b7fffe6f.png)
![TriangleAnimation-1](https://user-images.githubusercontent.com/52406963/62411089-3ebdce00-b60c-11e9-802d-b63bf740d3e3.png)

Link: https://www.openprocessing.org/sketch/742219

**3.1: Explorations with Random function**

![Screen Shot 2019-08-02 at 1 19 35 PM](https://user-images.githubusercontent.com/52406963/62411128-91978580-b60c-11e9-88d4-a64b78c87fb3.png)
![Screen Shot 2019-08-02 at 1 19 41 PM](https://user-images.githubusercontent.com/52406963/62411131-978d6680-b60c-11e9-9a78-7bcc01a1de53.png)
![Screen Shot 2019-08-02 at 1 19 47 PM](https://user-images.githubusercontent.com/52406963/62411136-9ceab100-b60c-11e9-8026-3aaaf12a4fec.png)

Link: https://www.openprocessing.org/sketch/742221

 **3.2: Explorations with Random function**
![Screen Shot 2019-08-02 at 3 53 26 PM](https://user-images.githubusercontent.com/52406963/62411158-c3105100-b60c-11e9-95d5-c80ee56fe63a.png)
![Screen Shot 2019-08-02 at 3 53 30 PM](https://user-images.githubusercontent.com/52406963/62411160-c4da1480-b60c-11e9-8e3a-2e1d2aeee00e.png)
![Screen Shot 2019-08-02 at 3 53 36 PM](https://user-images.githubusercontent.com/52406963/62411162-c6a3d800-b60c-11e9-8664-53f0a99f732e.png)

Link: https://www.openprocessing.org/sketch/742223

**4: Looping Animations**

![TriangleAnimation](https://user-images.githubusercontent.com/52406963/62411215-7416eb80-b60d-11e9-91b1-facf1c18534f.gif)

Link: https://www.openprocessing.org/sketch/742222

![Dot-Animation](https://user-images.githubusercontent.com/52406963/62411235-9f99d600-b60d-11e9-94c3-fd9cfb25e9a6.gif)

Link: https://www.openprocessing.org/sketch/742224

**Comment by AishwaryaAnandSingh** [comment]
1. Occult Identity from name: 
![Occult6](https://user-images.githubusercontent.com/52406831/62461210-c8eb6b00-b7a1-11e9-84a8-87ddfaa7f177.gif)

Code Link: 
https://www.openprocessing.org/sketch/742555

2. Constellation from name :
<img width="696" alt="AISHWARYA" src="https://user-images.githubusercontent.com/52406831/62460482-be2fd680-b79f-11e9-86a8-180191a5ddbc.png">

Code Link:
https://www.openprocessing.org/sketch/742554

3. Truchet Tiling

a) Triangle
![Tiles1](https://user-images.githubusercontent.com/52406831/62460813-a3119680-b7a0-11e9-82a0-0ac1a5225f8f.gif)

Code Link:
https://www.openprocessing.org/sketch/742557

b) Arc
![Tile1](https://user-images.githubusercontent.com/52406831/62460922-f71c7b00-b7a0-11e9-8df5-1bd60a2f40a3.gif)

Code Link:
https://www.openprocessing.org/sketch/742558

c) Diagonal (Triangle)
![Tiles3](https://user-images.githubusercontent.com/52406831/62460998-3a76e980-b7a1-11e9-866c-6e6d40d7e25a.gif)

Code Link:
https://www.openprocessing.org/sketch/742559

d) Isometric cube
![Tiles53](https://user-images.githubusercontent.com/52406831/62461138-93468200-b7a1-11e9-9755-692b4b4457ed.gif)
![Tiles52](https://user-images.githubusercontent.com/52406831/62461143-9477af00-b7a1-11e9-9d37-d4a45e43e380.gif)
![Tiles5](https://user-images.githubusercontent.com/52406831/62461147-98a3cc80-b7a1-11e9-8c8f-44c633542133.gif)

Code Link:
https://www.openprocessing.org/sketch/742560

**Comment by shrav13** [comment]
Generated trees using name, surname and age as inputs
![tree](https://user-images.githubusercontent.com/33093334/63350433-0db6fa80-c37b-11e9-9d74-0da337a49ff4.jpg)
Code link : https://www.openprocessing.org/sketch/745747
